apiVersion: v1
kind: Service
metadata:
  name: lightscan-backend
  labels:
    app: lightscan
spec:
  selector:
    app: lightscan
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
